query all_credentials {
  credentials {
    id
    name
    description
    categories
    skills
    created_at
    pow
    image
    gate {
      creator {
        id
        name
        pfp
      }
      holders {
        id
        name
        pfp
      }
    }
    dao {
      name
      logo {
        id
      }
    }
  }
}

query credential($id: uuid!) {
  credentials_by_pk(id: $id) {
    id
    name
    description
    categories
    skills
    created_at
    pow
    image
    dao {
      name
      logo {
        id
      }
    }
  }
}
