query dao_pages {
  daos(limit: 10) {
    id
  }
}

query dao_profile($id: uuid!) {
  daos_by_pk(id: $id) {
    id
    name
    description
    background_url
    logo_url
    categories
    socials {
      network
      url
    }
    gates {
      id
      title
      description
      categories
      image
    }
  }
}

query dao_profile_people($id: uuid!) {
  daos_by_pk(id: $id) {
    followers_aggregate(where: {status: {_eq: "following"}}) {
      aggregate {
        count
      }
    }
    followers(where: {status: {_eq: "following"}}) {
      user {
        id
        name
        username
        pfp
      }
    }
  }
}
