query get_explore($id: uuid!) {
  me {
    ...current_user
    pfp
  }

  gates {
    id
    gate_name
    description
    categories
    badge
    dao {
      id
      logo_url
      name
    }
  }
  daos {
    id
    name
    logo_url
    background_url
    description
    categories
    created_at
    # gates {....}
    # user is following ?
  }
  people: users(where: {id: {_neq: $id}, name: {_neq: "", _is_null: false }}) {
    id
    name
    pfp
    about
  }
}
