query get_explore($id: uuid!) {
  user: users_by_pk (id: $id) {
    id
    name
    credentials {
      dao {
        name
      }
    }
    gate_progresses {
      id
      status
      gate {
         id
         badge
         gate_name
         categories
         dao {
           id
           logo_url
           name
         }
      }
    }
  }
  gates {
    id
    gate_name
    description
    categories
    badge
    dao {
      id
      logo_url
      name
    }
  }
  daos {
    id
    name
    logo_url
    background_url
    description
    categories
    created_at
    # gates {....}
    # user is following ?
  }
  people: users(where: {id: {_neq: $id}}) {
    id
    name
    pfp
    about
  }
}
