query all_gates {
  gates {
    id
    title
    description
    categories
    skills
    published
    links
    image
  }
}

fragment gate_data on gates {
id
    title
    description
    categories
    skills
    published
    links
    image
    type
    creator {
      id
      name
      username
      pfp
      picture {
        ...file
      }
    }
    holder_count
    holders(limit: 4) {
      id
      name
      username
      pfp
      wallet
      picture {
        ...file
      }
    }
    dao {
      id
      name
      slug
      logo_url
      logo {
        id
        blur
      }
    }
    tasks {
      description
      gate_id
      id
      task_data
      task_type
      title
      order
    }
}

query gate($id: uuid!) {
  gates_by_pk(id: $id) {
    ...gate_data
  }
}

query gate_new($id: uuid!) {
  gates_by_pk(id: $id) {
    ...gate_data
  	whitelisted_wallets {
      wallet
    }
  }
}

query GateProgress($gateID: uuid!, $userID: uuid!) {
  gate_progress(
    where: { gate_id: { _eq: $gateID }, user_id: { _eq: $userID } }
  ) {
    completed_at
  }
}
