query get_credential($credential_id: uuid!) {
  credentials_by_pk(id: $credential_id) {
    name
    attitudes
    ceramic
    created_at
    description
    details
    group_id
    id
    image
    info
    issuer_id
    knowledges
    namespace
    pow
    skills
    status
    target_id
    updated_at
  }
}
