query get_home($id: uuid!) {
  user: users_by_pk(id: $id) {
    id
    name
    credentials {
      dao {
        name
      }
    }
    gate_progresses {
      gate {
        id
      }
      status
    }
  }
  gates {
    id
    gate_name
    description
    categories
    badge
    dao {
      id
      logo_url
      name
    }
  }
  daos {
    id
    name
    logo_url
    background_url
    description
    categories
    created_at
    # gates {....}
    # user is following ?
  }
  people: users(where: { id: { _neq: $id } }) {
    id
    name
    pfp
    about
  }
}
