query get_home {
  gates(limit: 4) {
    id
    title
    description
    categories
    image
    dao {
      id
      logo_url
      name
    }
  }
  daos(limit: 4) {
    id
    name
    logo_url
    background_url
    description
    categories
    created_at
    # gates {....}
    # user is following ?
  }
  people: users(limit: 9) {
    id
    name
    #pfp
    about
    username
  }
}
