query search($query: String!) {
  gates: search_gates(args: {search: $query}) {
    id
    title
    description
    categories
    skills
    published
    links
    image
  }
  credentials: search_credentials(query: $query) {
    hits
  }
  daos: search_daos(args: {search: $query}) {
    id
    name
    slug
    logo {
      ...file
    }
    logo_url
    background {
      ...file
    }
    followers_aggregate {
      aggregate {
        count
      }
    }
    gates_aggregate {
      aggregate {
        count
      }
    }
    background_url
    description
    categories
    permissions {
      user_id
      permission
    }
  }
  users: search_users(args: {search: $query}) {
    ...public_user
    pfp
  }
}

query search_daos($ids: [uuid!]) {
  daos(where: {id: {_in: $ids}}) {
    id
    name
    slug
    logo {
      ...file
    }
    logo_url
    background {
      ...file
    }
    followers_aggregate {
      aggregate {
        count
      }
    }
    gates_aggregate {
      aggregate {
        count
      }
    }
    background_url
    description
    categories
    permissions {
      user_id
      permission
    }
  }
}
