query credentials {
  credentials {
    id
  }
}

query credential($id: String!) {
  credential(id: $id) {
    id
    title
    description
    expirationDate
    status
    tags
    claim
    arweaveInfo

    claimArray {
      description
      type
      property
      label
      value
      metadata
    }

    issuer {
      primaryWallet {
        address
      }
    }

    recipient {
      primaryWallet {
        address
      }
    }

    dataModel {
      id
      title
      tags
      schema
      arweaveInfo
      createdAt
    }

    createdAt
    updatedAt
  }
}

query findCredentialsByDataModel($dataModelId: String!) {
  findCredentialsByDataModel(dataModelId: $dataModelId) {
    id
    title
    image
    tags
    issuer {
      id
    }
    recipient {
      id
    }
    createdAt
    status
  }
}
