query credentials {
  credentials {
    id
  }
}

query credential($id: String!) {
  credential(id: $id) {
    ...credential_info

    activities {
      newStatus
      oldStatus
      type
      oldUrl
      newUrl
      timestamp
      credential {
        id
      }
    }

    issuerOrganization {
      gatewayId
    }

    nft {
      chain
      minted
      txHash
    }

    claimArray {
      description
      type
      property
      label
      value
      metadata
    }

    issuerUser {
      gatewayId
      primaryWallet {
        address
      }
    }

    issuerOrganization {
      gatewayId
      name
      description
    }

    recipientUser {
      gatewayId
      primaryWallet {
        address
        chain
      }
    }

    dataModel {
      id
      title
      tags
      schema
      arweaveInfo
      createdAt
    }
  }
}



query findCredentialsByIssuerUser(
  $issuerUserId: String!
  $take: Float!
  $skip: Float!
) {
  findCredentialsByIssuerUser(
    issuerUserId: $issuerUserId
    take: $take
    skip: $skip
  ) {
    ...credential_info

    issuerUser {
      gatewayId
    }
    recipientUser {
      gatewayId
      id
      primaryWallet {
        address
        chain
      }
    }
  }
}

query findCredentialsByIssuerOrganization(
  $issuerOrganizationId: String!
  $take: Float!
  $skip: Float!
) {
  findCredentialsByIssuerOrganization(
    issuerOrganizationId: $issuerOrganizationId
    take: $take
    skip: $skip
  ) {
    ...credential_info

    issuerUser {
      gatewayId
    }
    recipientUser {
      gatewayId
      id
      primaryWallet {
        address
        chain
      }
    }
  }
}

query findCredentialsByRecipientUser(
  $recipientUserId: String!
  $take: Float!
  $skip: Float!
) {
  findCredentialsByRecipientUser(
    recipientUserId: $recipientUserId
    take: $take
    skip: $skip
  ) {
    ...credential_info

    issuerUser {
      gatewayId
    }
    recipientUser {
      gatewayId
      id
      primaryWallet {
        address
        chain
      }
    }
  }
}

query getUserCredentialCount($userId: String!) {
  totalIssued: getTotalodCredentialsIssuedByUser(userId: $userId)
  totalReceived: getTotalodCredentialsReceivedByUser(userId: $userId)
}

query getUserRelatedCredential(
  $userId: String!
  $take: Float!
  $skip: Float!
) {
  findCredentialsByIssuerUser(
    issuerUserId: $userId
    take: $take
    skip: $skip
  ) {
    ...credential_info

    issuerUser {
      gatewayId
    }
    recipientUser {
      gatewayId
      id
      primaryWallet {
        address
        chain
      }
    }
  }

  findCredentialsByRecipientUser(
    recipientUserId: $userId
    take: $take
    skip: $skip
  ) {
    ...credential_info

    issuerUser {
      gatewayId
    }
    recipientUser {
      gatewayId
      id
      primaryWallet {
        address
        chain
      }
    }
  }

  totalIssued: getTotalodCredentialsIssuedByUser(userId: $userId)
  totalReceived: getTotalodCredentialsReceivedByUser(userId: $userId)
}
