query findRecipientsByDataModel(
  $dataModelId: String!
  $take: Float!
  $skip: Float!
) {
  findRecipientsByDataModel(
    dataModelId: $dataModelId
    take: $take
    skip: $skip
  ) {
    id
    createdAt
  }
}
