query userByWallet($wallet: String!) {
  userByWallet(wallet: $wallet) {
    id
  }
}

query meProtocol {
  me {
    id
    isCompleted
    primaryWallet {
      id
      address
    }
    accesses {
      organization {
        id
        gatewayId
        name
      }
    }
    issuedCredentials {
      dataModel {
        id
      }
      id
      nft {
        minted
      }
    }
    totalOfIssuedCredentials
    totalOfreceivedCredentials
  }
}

query meProtocolCheck {
  me {
    id

    issuedCredentials {
      dataModel {
        id
      }
    }
  }
}
