query protocol_credentials {
  protocol_credential {
    id
  }
}

query protocol_credential($id: String!) {
  protocol {
    credential(id: $id) {
      id
      title
      description
      image
      expirationDate
      status
      tags
      claim
      qrCode
      arweaveInfo
      recipientAuth {
        id
      }

      createdAt
      updatedAt

      activities {
        newStatus
        oldStatus
        type
        oldUrl
        newUrl
        timestamp
        credential {
          id
        }
      }

      nft {
        chain
        minted
        txHash
      }

      claimArray {
        description
        type
        property
        label
        value
        metadata
      }

      issuerUser {
        id
        gatewayId
        primaryWallet {
          address
        }
      }

      issuerOrganization {
        id
        gatewayId
        name
        description
      }

      recipientUser {
        id
        gatewayId
        primaryWallet {
          address
          chain
        }
      }

      dataModel {
        id
        title
        tags
        schema
        arweaveInfo
        createdAt
      }
    }
  }
}

query protocol_find_credential_by_data_model(
  $dataModelId: String!
  $take: Float!
  $skip: Float!
) {
  protocol {
    findCredentialsByDataModel(
      dataModelId: $dataModelId
      skip: $skip
      take: $take
    ) {
      ...find_protocol_info
    }
  }
}

query protocol_find_credentials_by_issuer_user(
  $issuerUserId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      _or: [
        { issuerAuth: { userId: { _eq: $issuerUserId } } }
        { issuerUserId: { _eq: $issuerUserId } }
      ]
    }
    limit: $take
    offset: $skip
  ) {
    id
    title
    description
    image
    expirationDate
    status
    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }
  }
}

query protocol_find_credentials_by_issuer_organization(
  $issuerOrganizationId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: { issuerOrganizationId: { _eq: $issuerOrganizationId } }
    offset: $skip
    limit: $take
  ) {
    id
    title
    description
    image
    expirationDate
    status
    tags
    claim
    qrCode
    arweaveInfo

    createdAt
    updatedAt

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }
  }
}

query protocol_find_credentials_by_recipient_user(
  $recipientUserId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      _or: [
        { recipientAuth: { userId: { _eq: $recipientUserId } } }
        { recipientUserId: { _eq: $recipientUserId } }
      ]
    }
    limit: $take
    offset: $skip
  ) {
    id
    title
    description
    image
    expirationDate
    status
    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }
  }
}

query protocol_find_credentials_by_campaign(
  $recipientUserId: uuid!
  $dataModelId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      _and: [
        { dataModelId: { _eq: $dataModelId } }
        { recipientAuth: { userId: { _eq: $recipientUserId } } }
      ]
    }
    offset: $skip
    limit: $take
  ) {
    id
    title
    description
    image
    expirationDate
    status
    tags
    claim
    qrCode
    arweaveInfo
    createdAt
    updatedAt
    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
      }
    }
    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
      }
    }
    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
      }
    }
    nft {
      minted
    }
  }
}

query protocol_user_credential_count($userId: uuid!) {
  totalIssued: protocol_credential_aggregate(
    where: {
      _or: [
        { issuerAuth: { userId: { _eq: $userId } } }
        { issuerUserId: { _eq: $userId } }
      ]
    }
  ) {
    aggregate {
      count
    }
  }
  totalReceived: protocol_credential_aggregate(
    where: {
      _or: [
        { recipientAuth: { userId: { _eq: $userId } } }
        { recipientUserId: { _eq: $userId } }
      ]
    }
  ) {
    aggregate {
      count
    }
  }
}
