query protocol_credentials {
  protocol_credential {
    id
  }
}


query protocol_credential($id: String!) {
  protocol {
    credential(id: $id) {
      id
      title
      description
      image
      expirationDate
      status
      tags
      claim
      qrCode
      arweaveInfo

      createdAt
      updatedAt

      activities {
        newStatus
        oldStatus
        type
        oldUrl
        newUrl
        timestamp
        credential {
          id
        }
      }

      issuerOrganization {
        gatewayId
      }

      nft {
        chain
        minted
        txHash
      }

      claimArray {
        description
        type
        property
        label
        value
        metadata
      }

      issuerUser {
        gatewayId
        primaryWallet {
          address
        }
      }

      issuerOrganization {
        gatewayId
        name
        description
      }

      recipientUser {
        gatewayId
        primaryWallet {
          address
          chain
        }
      }

      dataModel {
        id
        title
        tags
        schema
        arweaveInfo
        createdAt
      }
    }
  }
}

query protocol_find_credential_by_data_model(
  $dataModelId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      dataModelId: {_eq: $dataModelId}
    }
    offset: $skip
    limit: $take
  ) {
    ...protocol_credential_info

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}

query protocol_find_credentials_by_issuer_user(
  $issuerUserId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      issuerUserId: {_eq: $issuerUserId}
    }
    offset: $skip
    limit: $take
  ) {
    id
    title
    description
    image
    expirationDate
    status
    tags
    claim
    qrCode
    arweaveInfo

    createdAt
    updatedAt

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}

query protocol_find_credentials_by_issuer_organization(
  $issuerOrganizationId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      issuerOrganizationId: {_eq: $issuerOrganizationId}
    }
    offset: $skip
    limit: $take
  ) {
    id
    title
    description
    image
    expirationDate
    status
    tags
    claim
    qrCode
    arweaveInfo

    createdAt
    updatedAt

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}

query protocol_find_credentials_by_recipient_user(
  $recipientUserId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      recipientUserId: {_eq: $recipientUserId}
    }
    offset: $skip
    limit: $take
  ) {
    id
    title
    description
    image
    expirationDate
    status
    tags
    claim
    qrCode
    arweaveInfo

    createdAt
    updatedAt

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}


query protocol_user_credential_count($userId: String!) {
  protocol {
    totalIssued: getTotalodCredentialsIssuedByUser(userId: $userId)
    totalReceived: getTotalodCredentialsReceivedByUser(userId: $userId)
  }
}
