fragment protocol_credential_info on protocol_credential {
  id
  title
  description
  image
  expirationDate
  status
  tags
  claim
  qrCode
  arweaveInfo

  createdAt
  updatedAt
}

fragment find_protocol_info on protocol_api_Credential {
  id
  title
  description
  image
  expirationDate
  status
  tags
  claim
  qrCode
  arweaveInfo

  createdAt
  updatedAt

  issuerUser {
    gatewayId
    id
    gatewayUser {
      name
      wallet
      picture {
        ...file
      }
    }
  }

  issuerOrganization {
    gatewayId
    hasuraOrganization {
      name
      logo_url
      logo {
        ...file
      }
    }
  }

  recipientUser {
    gatewayId
    id
    gatewayUser {
      name
      wallet
      picture {
        ...file
      }
    }
  }
}
