query credential($id: uuid!) {
  credentials_by_pk(id: $id) {
    id
    target_id
    name
    description
    categories
    created_at
    pow
    image
    uri
    status
    transaction_url
    gate {
      type
      creator {
        id
        name
        picture {
          ...file
        }
      }
      holders {
        id
        name
        pfp
      }
      tasks {
        id
      }
    }
    dao {
      name
      slug
      logo {
        ...file
      }
    }
  }
}

query count_total_holders($id: uuid!) {
  credentials_aggregate(where: { gate_id: { _eq: $id } }) {
    aggregate {
      count
    }
  }
}

query holders_by_gate($id: uuid!, $offset: Int!) {
  gates_by_pk(id: $id) {
    holders(limit: 6, offset: $offset) {
      id
      name
      username
      pfp
      wallet
      picture {
        ...file
      }
    }
  }
}

query holders_by_search($id: uuid!, $search: String!, $offset: Int!) {
  gates_by_pk(id: $id) {
    title
    holders(
      where: { _or: { name: { _ilike: $search } } }
      limit: 6
      offset: $offset
    ) {
      id
      name
      username
      pfp
      wallet
      picture {
        ...file
      }
    }
  }
}

query credential_by_user_id_by_gate_id($user_id: uuid!, $gate_id: uuid!) {
  credentials(
    where: { target_id: { _eq: $user_id }, gate_id: { _eq: $gate_id } }
  ) {
    credentials_protocol {
      id
      txHash
      nftId
    }
    gate {
      id
      title
      description
      categories

      published
      links
      image
      type
      creator {
        id
        name
        username
        pfp
        picture {
          ...file
        }
      }
      claim_limit
      expire_date
      holder_count
      holders(limit: 4) {
        id
        name
        username
        pfp
        wallet
        picture {
          ...file
        }
      }
      dao {
        id
        name
        slug
        logo_url
        logo {
          ...file
        }
      }
      tasks {
        description
        gate_id
        id
        task_data
        task_type
        title
        order
      }
      whitelisted_wallets {
        ens
        wallet
      }
      whitelisted_wallets_file {
        id
        metadata
      }

      loyalty_id
      points
      data_model_id
    }
    points
  }
}

query credential_by_user_id_by_gate_id_light($user_id: uuid!, $gate_id: uuid!) {
  credentials(
    where: { target_id: { _eq: $user_id }, gate: { id: { _eq: $gate_id } } }
  ) {
    credentials_protocol {
      id
      title
      claim
      txHash
      nftId
    }
    gate {
      id
      points
      published

      loyalty_id
      points
      data_model_id
    }
    points
  }
}

query credentials_by_user_id_by_loyalty_id(
  $user_id: uuid!
  $loyalty_id: uuid!
) {
  credentials(
    where: {
      target_id: { _eq: $user_id }
      gate: { loyalty_id: { _eq: $loyalty_id } }
    }
  ) {
    credentials_protocol {
      id
      txHash
      nftId
      image
    }
    gate {
      id
      points
      published
    }
    points
  }
}
