query direct_credential_info($gate_id: uuid!, $wallet: String!) {
  hasCredential: whitelisted_wallets_aggregate(
    where: { gate_id: { _eq: $gate_id }, user: { wallet: { _eq: $wallet } } }
  ) {
    aggregate {
      count
    }
  }
  whitelisted_wallets_aggregate(where: { gate_id: { _eq: $gate_id } }) {
    aggregate {
      count
    }
  }
}

query direct_credential_holders($gate_id: uuid!, $offset: Int!) {
  whitelisted_wallets(
    limit: 15
    offset: $offset
    where: { gate_id: { _eq: $gate_id } }
  ) {
    wallet
    user {
      id
      name
      username
      pfp
      picture {
        ...file
      }
    }
    gate {
      title
      image
      id
    }
    created_at
  }
}

query direct_credential_holders_search(
  $gate_id: uuid!
  $offset: Int!
  $search: String!
) {
  whitelisted_wallets(
    limit: 15
    offset: $offset
    where: {
      gate_id: { _eq: $gate_id }
      _or: [
        { user: { name: { _ilike: $search } } }
        { user: { username: { _ilike: $search } } }
        { wallet: { _ilike: $search } }
      ]
    }
  ) {
    wallet
    user {
      id
      name
      username
      pfp
      picture {
        ...file
      }
    }
    gate {
      title
      image
      id
    }
    created_at
  }
}
