query all_gates {
  gates {
    id
    title
    description
    categories

    published
    links
    image
  }
}

query gate($id: uuid!) {
  gates_by_pk(id: $id) {
    id
    title
    description
    categories

    published
    links
    image
    type
    creator {
      id
      name
      username
      pfp
      picture {
        ...file
      }
    }
    claim_limit
    expire_date
    holder_count
    holders(limit: 4) {
      id
      name
      username
      pfp
      wallet
      picture {
        ...file
      }
    }
    dao {
      id
      name
      slug
      logo_url
      status
      logo {
        ...file
      }
    }
    tasks {
      description
      gate_id
      id
      task_data
      task_type
      title
      order
    }
    whitelisted_wallets {
      ens
      wallet
    }
    whitelisted_wallets_file {
      id
      metadata
    }

    loyalty_id
    points
    data_model_id
  }
}

query gate_info($id: uuid!) {
  gates_by_pk(id: $id) {
    id
    title
    description
    categories
    published
    links
    image
    type
    creator {
      id
      name
      username
      pfp
      picture {
        ...file
      }
    }
    claim_limit
    expire_date
    holder_count
    dao {
      id
      name
      slug
      logo_url
      status
      logo {
        ...file
      }
    }
    loyalty_id
    points
    data_model_id
  }
}

query get_create_gate($id: uuid!) {
  gates_by_pk(id: $id) {
    id
    title
    description
    categories
    published
    links
    image
    type
    creator {
      id
      name
      username
      pfp
      picture {
        ...file
      }
    }
    holder_count
    holders(limit: 4) {
      id
      name
      username
      pfp
      wallet
      picture {
        ...file
      }
    }
    dao {
      id
      name
      slug
      logo_url
      logo {
        ...file
      }
    }
    tasks {
      description
      gate_id
      id
      task_data
      task_type
      title
      order
    }
    whitelisted_wallets_file {
      id
      metadata
    }
  }
}

query verify_csv_progress($file_id: uuid!) {
  verify_csv_progress(id: $file_id) {
    id
    invalid
    invalidList
    isDone
    total
    uploadedTime
    valid
    validList
  }
}

query GateProgress($gateID: uuid!, $userID: uuid!) {
  credentials(
    where: { gate_id: { _eq: $gateID }, target_id: { _eq: $userID } }
  ) {
    created_at
  }
}

query get_protocol_by_gate_id($user_id: String!, $gate_id: String!) {
  get_protocol_by_gate_id(user_id: $user_id, gate_id: $gate_id) {
    credential
  }
}
