query loyalty_programs($take: Int!, $skip: Int!) {
  loyalty_program(limit: $take, offset: $skip) {
    ...loyalty
  }
}

query loyalty_program($id: uuid!) {
  loyalty_program_by_pk(id: $id) {
    ...loyalty
  }
}

query loyalty_programs_by_organization_id($id: uuid!) {
  loyalty_program(where: { organization_id: { _eq: $id } }) {
    ...loyalty
  }
}

query loyalty_credential($dm_id: uuid!, $user_id: uuid!) {
  protocol_credential(
    where: { dataModelId: { _eq: $dm_id }, recipientUserId: { _eq: $user_id } }
  ) {
    id
    title
    claim
    txHash
    nftId
  }
}
