query me {
  me {
    ...current_user
    permissions {
      gate_id
      dao_id
      dao {
        is_admin
      }
      permission
    }
    picture {
      ...file
    }
    following {
      user_id
    }
    task_progresses {
      id
      task_id
      gate_id
      completed
      updated_at
    }
    following_dao(
      where: { status: { _eq: "following" }, dao: { id: { _is_null: false } } }
    ) {
      dao_id
      dao {
        id
        logo_url
        slug
        name
        is_admin
        logo {
          ...file
        }
      }
    }
    # TODO: ADMIN DAOS
  }
}

query me_user_info {
  me {
    ...current_user

    picture {
      ...file
    }
  }
}

query me_permissions {
  me {
    permissions {
      gate_id
      dao_id
      dao {
        is_admin
      }
      permission
    }
  }
}

query me_following {
  me {
    following {
      user_id
    }
    following_dao(
      where: { status: { _eq: "following" }, dao: { id: { _is_null: false } } }
    ) {
      dao_id
      dao {
        id
        logo_url
        slug
        name
        is_admin
        logo {
          ...file
        }
      }
    }
  }
}

query me_task_progresses {
  me {
    task_progresses {
      id
      task_id
      gate_id
      completed
      updated_at
    }
  }
}

query me_notification_settings {
  me {
    notification_settings {
      dapp_enabled
      dapp_optout
      email_enabled
      email_optout
    }
  }
}

query me_protocol {
  protocol {
    me {
      id
      isCompleted
      primaryWallet {
        id
        address
      }
      accesses {
        organization {
          id
          gatewayId
          name
        }
      }
      receivedCredentials {
        id
      }
    }
  }
}

query gatewayId {
  protocol {
    me {
      gatewayId
    }
  }
}
