fragment loyalty on loyalty_program {
  id
  name
  description
  image
  categories
  data_model_id
  organization_id
  categories
  loyalty_tiers {
    id
    tier
    min_pts
    max_pts
    image
  }
  gates {
    id
    title
    description
    image
    published
    categories
    data_model_id
    expire_date
    tasks {
      id
    }
  }
}
