query user_notifications($address: String!) {
  identity(address: $address, network: ETH) {
    unreadNotificationCount(namespaces: ["GatewayDAO"])
    notifications(namespaces: ["GatewayDAO"]) {
      list {
        network
        namespace
        id
        toAddress
        hasRead
        type
        timestamp
        ... on BiConnectReceivedNotification {
          fromAddress
        }
        ... on BiConnectAcceptedNotification {
          fromAddress
        }
      }
    }
    bidirectionalFriends{
      list {
        bidirectionalConnection {
          namespace
          from
          to
          state
        }
      }
    }
    friendRequestsInbox(after: "-1") {
      list {
        bidirectionalConnection {
          network
          direction
          namespace
          from
          to
          state
        }
      }
    }
    friendRequestsSent(after: "-1") {
      list {
        bidirectionalConnection {
          namespace
          from
          to
          state
        }
      }
    }
  }
}
