query findRecipientsByDataModel(
  $dataModelId: String!
  $take: Float!
  $skip: Float!
) {
  findRecipientsByDataModel(
    dataModelId: $dataModelId
    take: $take
    skip: $skip
  ) {
    id
    createdAt
    receivedCredentials {
      id
      expirationDate
      recipientUser {
        id
        gatewayId
      }
      createdAt
      image
    }
    createdAt
    totalOfreceivedCredentials
  }
}


query findRecipientsByDataModelCreditScore(
  $dataModelId: String!
  $take: Float!
  $skip: Float!
) {
  findRecipientsByDataModel(
    dataModelId: $dataModelId
    take: $take
    skip: $skip
  ) {
    id
    gatewayId
  }
}
