const ROUTES = {
  TERMS: '/terms',
  EXPLORE: '/explore',
  EXPLORE_EARN: '/explore/earn',
  EXPLORE_PASSES: '/explore/passes',
  EXPLORE_ISSUE: '/explore/issue',
  EXPLORE_ORGANIZATIONS: '/explore/organizations',
  SEARCH: '/search/[key]',
  AUTHENTICATION: '/authentication',
  CREDENTIALS: '/credentials',
  CREDIT_SCORE: '/creditscore',
  ALTITUDE: '/altitude-testnet',
  CREDENTIALS_NEW: '/credentials/new',
  EARNED: '/earned/[id]',
  DAO_PROFILE: '/org/[slug]',
  MY_PROFILE: '/profile',
  PROFILE: '/profile/[username]',
  PROFILE_EDIT: '/profile/edit',
  SETTINGS: '/settings',
  SETTINGS_PUBLIC_PROFILE: '/settings/public-profile',
  SETTINGS_ACCOUNT_MANAGEMENT: `${process.env.NEXT_PUBLIC_DASHBOARD_URL}/dashboard/user/settings`,
  SETTINGS_CONNECTED_ACCOUNTS: '/settings/connected-accounts',
  SETTINGS_DEVELOPER_PORTAL: '/settings/developer-portal',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  DAO_EDIT: '/org/[slug]/edit',
  DAO_NEW: '/org/new',
  GATE_PROFILE: '/credential/[id]',
  GATE_NEW: '/credential/new',
  PROTOCOL_CREDENTIAL: `${process.env.NEXT_PUBLIC_DASHBOARD_URL}/dashboard/user/asset/[id]`,
  PROTOCOL_DATAMODEL: `${process.env.NEXT_PUBLIC_DASHBOARD_URL}/explorer/data-models/[id]`,
  PROTOCOL_DATAMODEL_ISSUERS: `${process.env.NEXT_PUBLIC_DASHBOARD_URL}/explorer/data-models/[id]/issuers`,
  PROTOCOL_DATAMODEL_RECIPIENTS: '/model/[id]/recipients',
  PROTOCOL_DATAMODEL_CREDENTIALS: '/model/[id]/credentials',
  PROTOCOL_DATAMODEL_PLAYGROUND: '/model/[id]/playground',
  PROTOCOL_DATAMODEL_CREDENTIAL_CREATE: '/model/[id]/credentials/create',
  LOYALTY_PROGRAM: '/loyalty/[id]',
  LOYALTY_PROGRAM_CREDENTIAL: '/loyalty/credential/[id]',
};

module.exports = {
  ROUTES,
};
