fragment public_user on users {
  id
  name
  #pfp
  username
  #init
  about # Soon to be deprecated
  bio
  pic_id
  skills
  languages
  timezone
  picture {
    ...file
  }
  cover {
    ...file
  }
  socials {
    network
    url
  }
}

fragment current_user on users {
  ...public_user
  email_address
  init

  # credentials {
  #   dao {
  #     name
  #   }
  # }
  # gate_progresses {
  #   gate {
  #     id
  #   }
  #   status
  # }
}
