fragment current_user on users {
  id
  name
  #pfp
  username
  email_address
  init
  about
  skills
  knowledges
  attitudes
  discord_id
  socials {
    network
    user_id
  }

  # credentials {
  #   dao {
  #     name
  #   }
  # }
  # gate_progresses {
  #   gate {
  #     id
  #   }
  #   status
  # }
}
