fragment experience on experiences {
  dao {
    name
    logo {
      ...file
    }
    logo_url
  }
  credentials {
    id
    name
    image
    description
    categories
    status
  }
  start_date
  end_date
  working
  description
  visible
}

fragment public_user on users {
  id
  name
  #pfp
  username
  #init
  about # Soon to be deprecated
  bio
  pic_id
  skills
  languages
  timezone
  wallet
  following_aggregate {
    aggregate {
      count
    }
  }
  credentials {
    id
  }
  picture {
    ...file
  }
  cover {
    ...file
  }
  socials {
    network
    url
  }

  experiences {
    ...experience
  }
}

fragment current_user on users {
  ...public_user
  email_address
  init

  experiences {
    ...experience
    hidden_credentials {
      credential {
        id
        name
        image
        description
        categories
      }
    }
  }

  # credentials {
  #   dao {
  #     name
  #   }
  # }
  # gate_progresses {
  #   gate {
  #     id
  #   }
  #   status
  # }
}
