fragment loyalty on loyalty_program {
  id
  name
  description
  image
  categories
  data_model_id
  organization_id
  categories
  details
  gates(order_by: { updated_at: desc }) {
    id
    title
    description
    image
    published
    categories
    data_model_id
    expire_date
    points
    tasks {
      id
    }
    claim_limit
    holder_count
    type
    published
    updated_at
    created_at
  }
  details
  loyalty_tiers {
    tier
    id
    image
    max_pts
    min_pts
  }
  dao {
    background_url
    name
    logo_url
    slug
    id
    logo {
      s3_key
      id
    }
  }
}
