query credentials {
  credentials {
    id
  }
}

query findCredentialsByDataModel(
  $dataModelId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      dataModelId: {_eq: $dataModelId}
    }
    offset: $skip
    limit: $take
  ) {
    ...protocol_credential_info

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}

query findCredentialsByIssuerUser(
  $issuerUserId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      issuerUserId: {_eq: $issuerUserId}
    }
    offset: $skip
    limit: $take
  ) {
    ...protocol_credential_info

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}

query findCredentialsByIssuerOrganization(
  $issuerOrganizationId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      issuerOrganizationId: {_eq: $issuerOrganizationId}
    }
    offset: $skip
    limit: $take
  ) {
    ...protocol_credential_info

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}

query findCredentialsByRecipientUser(
  $recipientUserId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_credential(
    where: {
      recipientUserId: {_eq: $recipientUserId}
    }
    offset: $skip
    limit: $take
  ) {
    ...protocol_credential_info

    issuerUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }

    issuerOrganization {
      gatewayId
      hasuraOrganization {
        name
        logo_url
        logo {
          ...file
        }
      }
    }

    recipientUser {
      gatewayId
      id
      gatewayUser {
        name
        wallet
        picture {
          ...file
        }
      }
    }
  }
}
