query dataModels($take: Int!, $skip: Int!) {
  protocol_data_model(limit: $take, offset: $skip) {
    id
    title
    tags
    version
    description
    createdBy {
      gatewayUser {
        name
        picture {
          id
          s3_key
          blur
        }
      }
      gatewayId
    }
  }
}

query findRecipientsByDataModel($dataModelId: uuid!, $take: Int!, $skip: Int!) {
  protocol_user(
    where: { credentials: { dataModelId: { _eq: $dataModelId } } }
    limit: $take
    offset: $skip
  ) {
    id
    gatewayId
    gatewayUser {
      name
      pfp
      picture {
        id
        s3_key
        blur
      }
    }
  }
}

query findCredentialsByDataModelProtocol(
  $dataModelId: uuid!
  $take: Int!
  $skip: Int!
) {
  protocol_data_model_by_pk(id: $dataModelId) {
    credentials(limit: $take, offset: $skip, order_by: { createdAt: desc }) {
      id
      tags
      status
      issuerUser {
        gatewayId
        id
      }
      recipientUser {
        id
        gatewayId
      }
      status
    }
  }
}
