query getTotalCredentialsByDataModelGroupByIssuer($dataModelId: String!) {
  getTotalCredentialsByDataModelGroupByIssuer(dataModelId: $dataModelId)
}

query getDataModelStats($dataModelId: String!) {
  getTotalofIssuersByDataModel(dataModelId: $dataModelId)
  getTotalCredentialsByDataModelGroupByRecipient(dataModelId: $dataModelId)
  getTotalCredentialsByDataModel(dataModelId: $dataModelId)
}

query getDaoStats($organizationId: String!) {
  getTotalodCredentialsIssuedByOrganization(userId: $organizationId)
}
