fragment credential_info on Credential {
  id
  title
  description
  image
  expirationDate
  status
  tags
  claim
  qrCode
  arweaveInfo
  suspensionConditions
  revocationConditions
  updateConditions

  createdAt
  updatedAt
}
