fragment dao_profile on daos {
  id
  name
  description
  slug
  background {
    ...file
  }
  logo {
    ...file
  }
  logo_url
  background_url
  categories
  socials {
    network
    url
  }
  gates(where: { published: { _eq: "published" } }, limit: 3) {
    id
    title
    description
    categories
    image
    published
  }
  followers_aggregate(where: { status: { _eq: "following" } }) {
    aggregate {
      count
    }
  }
  gates_aggregate {
    aggregate {
      count
    }
  }
  protocolOrganization {
    gatewayId
    id
    name
    organization_accesses {
      user {
        gatewayId
      }
      role
    }
  }
}

query dao_pages {
  daos(limit: 10) {
    id
    slug
  }
}

query dao_profile($id: uuid!) {
  daos_by_pk(id: $id) {
    ...dao_profile
    followers(where: { status: { _eq: "following" } }, limit: 6) {
      user {
        id
        name
        username
        pfp
        picture {
          ...file
        }
        permissions(where: { dao_id: { _eq: $id } }) {
          permission
        }
      }
    }
  }
}

query dao_profile_by_slug($slug: String!) {
  daos(where: { slug: { _eq: $slug } }) {
    ...dao_profile
    followers(where: { status: { _eq: "following" } }, limit: 6) {
      user {
        id
        name
        username
        pfp
        picture {
          ...file
        }
        permissions(where: { dao: { slug: { _eq: $slug } } }) {
          permission
        }
      }
    }
  }
}

query dao_gates_tab($id: uuid!) {
  daos_by_pk(id: $id) {
    gates {
      id
      title
      description
      categories
      image
      published
      dao {
        id
      }
    }
  }
}

query dao_profile_people($id: uuid!, $offset: Int!) {
  daos_by_pk(id: $id) {
    followers(
      where: { status: { _eq: "following" } }
      order_by: { user: { name: asc } }
      limit: 15
      offset: $offset
    ) {
      user {
        id
        name
        username
        pfp
        picture {
          ...file
        }
        permissions(where: { dao_id: { _eq: $id } }) {
          permission
        }
      }
    }
  }
}

mutation create_dao(
  $logo_id: uuid!
  $name: String!
  $description: String!
  $categories: jsonb!
  $background_id: uuid!
  $socials: [dao_socials_insert_input!]!
) {
  insert_daos_one(
    object: {
      logo_id: $logo_id
      name: $name
      description: $description
      categories: $categories
      background_id: $background_id
      socials: { data: $socials }
    }
  ) {
    id
    logo_url
    name
    is_admin
    slug
    logo {
      ...file
    }
  }
}

mutation edit_dao(
  $id: uuid!
  $logo_id: uuid!
  $name: String!
  $description: String!
  $categories: jsonb!
  $background_id: uuid!
  $socials: [dao_socials_insert_input!]!
) {
  update_daos_by_pk(
    _set: {
      logo_id: $logo_id
      name: $name
      description: $description
      categories: $categories
      background_id: $background_id
    }
    pk_columns: { id: $id }
  ) {
    id
    logo_url
    name
    is_admin
    slug
    logo {
      ...file
    }
  }
  delete_dao_socials(where: { dao_id: { _eq: $id } }) {
    affected_rows
  }
  insert_dao_socials(objects: $socials) {
    affected_rows
  }
}

mutation dao_set_user_admin(
  $dao_id: uuid!
  $user_id: uuid!
  $permission: permission_types = "dao_admin"
) {
  insert_permissions(
    objects: { dao_id: $dao_id, user_id: $user_id, permission: $permission }
    on_conflict: {
      constraint: permissions_dao_id_user_id_credential_id_key
      update_columns: [permission]
    }
  ) {
    affected_rows
  }
}

mutation dao_set_user_member(
  $dao_id: uuid!
  $user_id: uuid!
  $permission: permission_types = "member"
) {
  insert_permissions(
    objects: { dao_id: $dao_id, user_id: $user_id, permission: $permission }
    on_conflict: {
      constraint: permissions_dao_id_user_id_credential_id_key
      update_columns: [permission]
    }
  ) {
    affected_rows
  }
}
