query dataModel($id: String!) {
  protocol {
    dataModel(id: $id) {
      id
      description
      schema
      tags
      title
      arweaveInfo
      createdAt
      createdBy {
        gatewayId
      }
    }
  }
}

query dataModels($limit: Int!, $offset: Int!) {
  protocol_data_model(limit: $limit, offset: $offset) {
    id
    title
    tags
    version
    description
    createdBy {
      gatewayId
    }
  }
}
