query get_home($daos_where: daos_bool_exp = {}) {
  gates(
    where: { published: { _eq: "published" } }
    limit: 4
    order_by: { published_at: desc, updated_at: desc }
  ) {
    id
    title
    description
    categories
    image
    published
    dao {
      id
      logo_url
      slug
      logo {
        ...file
      }
      name
    }
  }
  daos(limit: 3, where: $daos_where) {
    id
    name
    slug
    logo {
      ...file
    }
    logo_url
    background {
      ...file
    }
    followers_aggregate {
      aggregate {
        count
      }
    }
    gates_aggregate {
      aggregate {
        count
      }
    }
    background_url
    description
    categories
    permissions {
      user_id
      permission
    }
  }
  people: users(limit: 9) {
    id
    name
    about
    username
    wallet
    picture {
      ...file
    }
  }
  # loyalty_program(limit: 4) {
  #   ...loyalty
  # }
}

query gates_tab {
  gates(order_by: { published_at: desc, updated_at: desc }) {
    id
    title
    description
    categories
    image
    published
    loyalty_id
    dao {
      id
      logo_url
      slug
      logo {
        ...file
      }
      name
    }
  }
}

query daos_tab {
  daos(order_by: { name: asc }) {
    id
    name
    slug
    logo {
      ...file
    }
    logo_url
    background {
      ...file
    }
    followers_aggregate {
      aggregate {
        count
      }
    }
    gates_aggregate {
      aggregate {
        count
      }
    }
    background_url
    description
    categories
    permissions {
      user_id
      permission
    }
  }
}
query people_tab($offset: Int!) {
  people: users(order_by: { name: asc }, limit: 15, offset: $offset) {
    id
    name
    picture {
      ...file
    }
    about
    username
    wallet
  }
}
