query loyaltys {
  loyalty_program {
    ...loyalty
  }
}

query loyalty($id: uuid!) {
  loyalty_program_by_pk(id: $id) {
    ...loyalty
    dao {
      background_url
      name
      logo
      logo_url
      slug
    }
  }
}
