query loyaltys {
  loyalty_program {
    ...loyalty
  }
}

query loyalty($id: uuid!) {
  loyalty_program_by_pk(id: $id) {
    ...loyalty
    dao {
      background_url
      name
      logo_url
      slug
    }
  }
}

query get_gate_progress_completed_by_loyalty_program($userId: uuid!, $loyaltyProgramId: uuid!) {
  gate_progress(
    where: {
      user_id: { _eq: $userId }
      status: { _eq: "completed" }
      gate: { loyalty_id: { _eq: $loyaltyProgramId } }
    }
  ) {
    gate_id
    gate {
      points
    }
  }
}
