query user_from_wallet($wallet: String!) {
  users(where: {wallet: {_eq: $wallet}}) {
    id
    wallet
    name
    username
    picture {
      ...file
    }
  }
}

query notification_settings($user_id: uuid!) {
  notification_settings_by_pk(user_id: $user_id) {
    dapp_enabled
    dapp_optout
    email_enabled
    email_optout
  }
}
